apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "serve-static.fullname" . }}
  labels:
    {{- include "serve-static.labels" . | nindent 4 }}
data:
  index.html: |-
    {{- .Values.html | nindent 4}}
